### ISSUE TITLE
since 14.06.2022 3:12, filesystem does missmatch db

### ISSUE THREAD

**Issue by abma** [spring/upq#86]
Traceback (most recent call last):
  File "/home/springfiles/upq/verify.py", line 47, in <module>
    raise Exception("db vs filesystem missmatch: %s" %str(diff))
Exception: db vs filesystem missmatch: {'/home/springfiles/upq/files/maps/otago_redux_1.0.sd7'}

**Comment by springraaar** [comment]
in what situation was that executed? when? Is that really a serious error? seems like it should be a warning.

That's probably due to this error report where i reverted the change a few hours later and subsequently fixed
https://springrts.com/phpbb/viewtopic.php?p=603412#p603412

At the moment that file exists in the file system and also has a record on the springfiles DB.

People have been able to upload maps normally throughout the next few days. I tested uploading some myself too.

**Comment by abma** [comment]
its run every hour by cron. and yes, this is a serious error as the list of files doesn't match the list of files in the database.

for the reference: https://github.com/spring/upq/blob/master/verify.py#L47

also atm the error is:

 Exception: db vs filesystem missmatch: {'/home/springfiles/upq/files/maps/otago_dx_1.0.sd7', '/home/springfiles/upq/files/maps/alexandra_1.0.sd7', '/home/springfiles/upq/files/games/micronwars2-_v0.23.sdz'}

**Comment by springraaar** [comment]
I had deleted the record for micronwars2-_v0.23 by mistake, but restored it now using a dump from 12 june (before i started making changes to the db).

**Comment by abma** [comment]
thanks for solving!
